---
- name: Install JDK 21 on Debian and Red Hat based systems
  hosts: all
  become: yes
  vars:
    jdk_version: 21
    openjdk_package_debian: "openjdk-{{ jdk_version }}-jdk"
    openjdk_package_redhat: "java-{{ jdk_version }}-openjdk-devel"

  tasks:
    - name: Detect OS family
      ansible.builtin.setup:
        filter: ansible_os_family

    - name: Install JDK on Debian-based systems
      ansible.builtin.apt:
        name: "{{ openjdk_package_debian }}"
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install JDK on Red Hat-based systems
      ansible.builtin.yum:
        name: "{{ openjdk_package_redhat }}"
        state: present
      when: ansible_os_family == 'RedHat'
